### ISSUE TITLE
vsCode tells me the version of Edge I am using is not supported.

### ISSUE THREAD

**Issue by nhdoublek** [Microsoft/vscode-edge-debug2#117]
I get the following error message in vsCode when I try to launch Edge in a debugging session.  I'm using the latest versions of vsCode and Edge.  Should it be supported?

"Your version of Edge does not support debugging via the Edge DevTools Protocol. You can read more about supported versions here (https://aka.ms/edp-docs)."

**Comment by rakatyal** [comment]
Hello,
What Windows OS version are you running on? Microsoft Edge DevTools Protocol works only on Windows 10 April 2018 Update and later builds.

**Comment by csjasonwong** [comment]
I have the same issue as well. I'm using Windows 10 with latest update in Nov 2018.

**Comment by csjasonwong** [comment]
And my Edge is Microsoft Edge 38.14393.2068.0

**Comment by Shenniey** [comment]
Hello, 

Thank you for the response. I'm sorry for the long response time. To get a better version of your OS version, can I ask what your OS build number is? You can find this by going to Start -> Settings -> System -> About, and then scrolling down to the Windows specifications. The latest OS build should be 17134.407.

@nhdoublek if you could, could you also provide your OS build number and Edge version?

**Comment by csjasonwong** [comment]
Windows 10 Pro. Version 1607 (OS Bu8ild 14393.2189)

**Comment by csjasonwong** [comment]
and My Edge is 38.14393.2068.0

**Comment by dhanvikapila** [comment]
@csjasonwong your version of Windows does not support Edge Developer protocol.  You need to be on Windows 10 April 2018 or later version. Windows 10 build number for supported OS should say "Version 1803".

**Comment by csjasonwong** [comment]
Ok Thanks!
