### ISSUE TITLE
[loc][Query][vscode_extensions ] Localizability of 0; "edge.url.description"

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/vscode-edge-debug2#133]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help please?
Thanks!

Source:
Will search for a tab with this EXACT url and attach to it, if found

File Name:
Src\vscode-extensions\vscode-edge-debug2.xlf

Resource ID:
0; "edge.url.description"

Query:
Please, could you confirm if "EXACT" can be translated in this sentence?

**Comment by PDostalek** [comment]
Please clarify the meaning of "attach" in this string...

**Comment by dhanvikapila** [comment]
Attach means that we will attach the debugger to this tab (specified using the URL) to debug javascript.

**Comment by PDostalek** [comment]
Translatable - **EXACT**? I assume not..please confirm

**Comment by dhanvikapila** [comment]
Not required to translate EXACT.  Thanks.
