### ISSUE TITLE
[loc][Query][vscode_extensions ] Localizability of 0; "edge.skipFiles.description"

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/vscode-edge-debug2#134]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help please?
Thanks!

Source:
An array of file or folder names, or path globs, to skip when debugging.

File Name:
Src\vscode-extensions\vscode-edge-debug2.xlf

Resource ID:
0; "edge.skipFiles.description"

Query:
Please explain the meaning of "path globs".

**Comment by dhanvikapila** [comment]
"path globs" are regexs used for specifying files and folders (e.g. "**/test*", "script.*", etc.)

**Comment by PDostalek** [comment]
Thanks
