### ISSUE TITLE
[loc][Query][vscode_extensions ] Localizability of 	 0; "edge.breakOnLoadStrategy.regex.description"

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/vscode-edge-debug2#135]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help please?
Thanks!

Source:
Sets breakpoints optimistically in files with the same name as the file in which the breakpoint is set.

File Name:
Src\vscode-extensions\vscode-edge-debug2.xlf

Resource ID:
0; "edge.breakOnLoadStrategy.regex.description"

Query:
What does optimistically mean in this context?

**Comment by dhanvikapila** [comment]
"optimistically" is meant to capture that there are some cases where the breakpoint will not be hit on the file where the breakpoint was set.  Can you think of a better way to capture that?

**Comment by PDostalek** [comment]
It should be enough Thanks for the reply
