### ISSUE TITLE
Add platform check

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-edge-debug2#64]
I started it on Mac just to see what would happen, and it just crashes with `Debug adapter process has terminated unexpectedly`. You should check the platform and fail with a nice message.

**Comment by rakatyal** [comment]
Thanks for reporting!

**Comment by rakatyal** [comment]
@roblourens: There was an issue with our first release. Could you try this with 1.0.1? I believe @mrcrane added a platform check which should cover this scenario.

**Comment by roblourens** [comment]
"Your version of Edge does not support debugging via the Edge DevTools Protocol. ..."

Close enough 😛
