### ISSUE TITLE
Non-existent watch variable doesn't say "not available"

### ISSUE THREAD

**Issue by rakatyal** [Microsoft/vscode-edge-debug2#68]
Affected Branch: RS4_release_webplat
Affected Build: OS. 17134
Affected Product Language: 

Steps to reproduce:

1. Use the latest Edge debug adapter.
2. Stop at a breakpoint.
3. Type an expression that does not calculate to a correct entity. Say "gibberishvariable1"

Actual:
The expressions added after we hit a breakpoint do not say "not available". They should say it.

![untitled](https://user-images.githubusercontent.com/12533467/40023915-6a5ecb80-5781-11e8-82a1-caad350bbf4f.png)

**Comment by Shenniey** [comment]
Fixed in release 1.0.6
