### ISSUE TITLE
Failed to add breakpoint to gutter after starting debugging

### ISSUE THREAD

**Issue by dhanvikapila** [Microsoft/vscode-edge-debug2#77]
**Repro Steps**:

1. Install vscode on clean RS4 OS.
3. Install edge debug adapter extension inside VS Code.
5. Copy \\scratch2\scratch\rakatyal\TestAppJavaScript to local machine "C:\test".
7. Install http-server using command: npm install http-server -g
9. Open the project you copy from step 3 in VS Code.
11. Start http-server from the directory of your project.
13. Add one breakpoint on line 1 of  "\src\test2.js".
15. Start debug with edge.
17. Breakpoint can be hit after refresh edge broswer.
19. Continue to add breakpoint on line 3 

**Expected**:
Breakpoint mark(red dot) appears in front of line3.

**Actual**:
Breakpoint mark(red dot) doesn't appears in front of line3.

**More info:**
if you hit continue, breakpoint of line3 can be hit.

**Comment by mrcrane** [comment]
Fixed for v1.0.2 release
