### ISSUE TITLE
Error is given when adding a watch variable that does not exist

### ISSUE THREAD

**Issue by changsi-an** [Microsoft/vscode-edge-debug2#8]
It will say "Cannot read property 'indexOf' of undefined.

It happens for both VS and VSCode.

<img width="715" alt="capture" src="https://user-images.githubusercontent.com/14335429/35892577-cbf221ea-0b5e-11e8-9f21-af190a4145ff.PNG">

**Comment by Shenniey** [comment]
This was taken care of in vscode-chrome-debug-core. Errors are no longer shown at all, e.g. https://github.com/Microsoft/vscode-chrome-debug-core/issues/173.
