### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by apexdesigns** [Microsoft/vscode-edge-debug2#86]
Having general performance issues with edge using this extension. Lunching the debugger produces very slow and choppy performance. CSS Animations show it the most. I would fault edge in general but when I load the website without the debugger attached. It runs at blazing speeds. Wondering if the hook process is whats killing the performance or just flags used to lunch edge. A private repo can be provided on request.

**Comment by apexdesigns** [comment]
Basic Info
Windows 10 1803
Edge  42.17134.1.0

**Comment by dhanvikapila** [comment]
@apexdesigns  can you please provide us with a simplistic repro? Based on your description it does sound like an Edge issue. We can take this to the Edge team if you can provide us with your repro project. Thanks for your feedback.
